#! Generated by gemini

import os
import sys
from collections import defaultdict
from pymediainfo import MediaInfo
import glob


# --- Helper Functions ---

def format_size(size_in_bytes):
    """Converts bytes into a human-readable format (KB, MB, GB)."""
    if size_in_bytes is None:
        return "N/A"
    power = 1024
    n = 0
    power_labels = {0: '', 1: 'K', 2: 'M', 3: 'G', 4: 'T'}
    while size_in_bytes >= power and n < len(power_labels):
        size_in_bytes /= power
        n += 1
    return f"{size_in_bytes:.2f} {power_labels[n]}B"


def format_duration(ms):
    """Converts milliseconds into HH:MM:SS format."""
    if ms is None:
        return "N/A"
    s = int(ms / 1000)
    m, s = divmod(s, 60)
    h, m = divmod(m, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def get_bitrate(rate):
    """Formats bitrate into a human-readable format (kb/s or Mb/s)."""
    if rate is None:
        return "N/A"
    rate = int(rate)
    if rate > 1_000_000:
        return f"{rate / 1_000_000:.2f} Mb/s"
    return f"{rate / 1_000:.0f} kb/s"


# --- Core Functions ---

def rename_files_with_no_extension(root_folder):
    """
    Scans a directory and its subdirectories.
    Any file without an extension is renamed to have a .mp4 extension.
    """
    print("--- Étape 1: Renommage des fichiers sans extension en .mp4 ---")
    renamed_count = 0
    for dirpath, _, filenames in os.walk(root_folder):
        for filename in filenames:
            # Check if the file has an extension
            if '.' not in filename:
                base_name, ext = os.path.splitext(filename)
                if not ext:
                    old_path = os.path.join(dirpath, filename)
                    new_path = os.path.join(dirpath, filename + '.mp4')
                    try:
                        os.rename(old_path, new_path)
                        print(f"Renommé : '{old_path}' -> '{new_path}'")
                        renamed_count += 1
                    except OSError as e:
                        print(f"Erreur en renommant '{old_path}': {e}")
    print(f"\nTerminé. {renamed_count} fichier(s) renommé(s).\n")


def generate_nfo(root_folder):
    """
    Scans for media files, extracts their metadata, and writes it
    to a single summary.nfo file in the root folder.
    """
    print("--- Étape 2: Génération du fichier .nfo ---")
    video_data = []
    audio_data = defaultdict(list)
    target_extensions = ('.mp4', '.webm', '.mp3')

    for dirpath, _, filenames in os.walk(root_folder):
        for filename in filenames:
            if filename.lower().endswith(target_extensions):
                file_path = os.path.join(dirpath, filename)
                print(f"Analyse de : {file_path}")
                try:
                    media_info = MediaInfo.parse(file_path)

                    if filename.lower().endswith(('.mp4', '.webm')):
                        # --- Categorie Video ---
                        info = {'path': file_path, 'audio_tracks': [], 'subtitle_tracks': []}
                        for track in media_info.tracks:
                            if track.track_type == 'General':
                                info['title'] = track.track_name or os.path.splitext(filename)[0]
                                info['format'] = track.format
                                info['duration'] = format_duration(track.duration)
                                info['size'] = format_size(track.file_size)
                            elif track.track_type == 'Video':
                                info['video_codec'] = track.format
                                info['video_bitrate'] = get_bitrate(track.bit_rate)
                                info[
                                    'resolution'] = f"{track.width}x{track.height}" if track.width and track.height else "N/A"
                                info['framerate'] = f"{track.frame_rate} FPS" if track.frame_rate else "N/A"
                                info['scan_type'] = track.scan_type
                            elif track.track_type == 'Audio':
                                info['audio_tracks'].append({
                                    'codec': track.format,
                                    'bitrate': get_bitrate(track.bit_rate),
                                    'channels': track.channel_s,
                                    'language': track.language
                                })
                            elif track.track_type == 'Text':
                                info['subtitle_tracks'].append({
                                    'format': track.format,
                                    'language': track.language
                                })
                        video_data.append(info)

                    # ... (START of the filled section for .mp3)
                    elif filename.lower().endswith('.mp3'):
                        # --- Categorie Audio Musique ---
                        info = {'path': file_path}
                        general_track = media_info.tracks[0]
                        audio_track = media_info.tracks[1] if len(media_info.tracks) > 1 else general_track

                        album = general_track.album or "Album Inconnu"
                        artist = general_track.performer or "Artiste Inconnu"
                        year = general_track.recorded_date or "Année Inconnue"

                        album_key = f"{artist} - {album} ({year})"

                        info['track_name'] = general_track.track_name or os.path.splitext(filename)[0]
                        info['size'] = format_size(general_track.file_size)
                        info['audio_codec'] = audio_track.format
                        info['duration'] = format_duration(general_track.duration)
                        info['bitrate'] = get_bitrate(audio_track.bit_rate or general_track.overall_bit_rate)
                        info[
                            'frequency'] = f"{int(audio_track.sampling_rate) / 1000} kHz" if audio_track.sampling_rate else "N/A"
                        info[
                            'bit_depth'] = f"{audio_track.bit_depth} bits" if audio_track.bit_depth else "N/A pour ce format"
                        audio_data[album_key].append(info)
                    # ... (END of the filled section for .mp3)

                except Exception as e:
                    print(f"Impossible de traiter le fichier '{file_path}': {e}")

    # --- Write NFO file ---
    nfo_path = os.path.join(root_folder, "summary.nfo")
    try:
        with open(nfo_path, 'w', encoding='utf-8') as f:
            # --- VIDEO SECTION ---
            if video_data:
                for info in sorted(video_data, key=lambda x: x['path']):
                    f.write(f"\n---[ .{info.get('path')[len(root_folder):]} ]---\n\n")
                    f.write("Général\n")
                    f.write(f"    Format: {info.get('format', 'N/A')}\n")
                    f.write(f"    Durée: {info.get('duration', 'N/A')}\n")
                    f.write(f"    Poids: {info.get('size', 'N/A')}\n\n")
                    f.write("Vidéo\n")
                    f.write(f"    Codec Video: {info.get('video_codec', 'N/A')}\n")
                    f.write(f"    Bitrate vidéo: {info.get('video_bitrate', 'N/A')}\n")
                    f.write(f"    Résolution: {info.get('resolution', 'N/A')}\n")
                    f.write(f"    Framerate: {info.get('framerate', 'N/A')}\n")
                    f.write(f"    Type de balayage: {info.get('scan_type', 'N/A')}\n\n")

                    for i, track in enumerate(info.get('audio_tracks', []), 1):
                        f.write(f"Audio #{i}\n")
                        f.write(f"    Codec(s) Audio: {track.get('codec', 'N/A')}\n")
                        f.write(f"    Bitrate(s) audio: {track.get('bitrate', 'N/A')}\n")

            # ... (START of the filled section for writing audio data)
            if audio_data:
                for album_key, info in sorted(audio_data.items()):
                    tracks = sorted(audio_data[album_key], key=lambda x: (
                        int(x['track_position'].split('/')[0]) if x.get('track_position') else 999, x['track_name']))
                    first_track = tracks[0]
                    # total_size = sum(t['size'] for t in tracks if t['size'] is not None)

                    f.write(f"\n---[ .{first_track.get('path')[len(root_folder):]} ]---\n\n")
                    f.write("Général\n")
                    f.write(f"    Durée: {first_track.get('duration', 'N/A')}\n")
                    f.write(f"    Poids: {first_track.get('size', 'N/A')}\n\n")
                    f.write(f"    Codec Audio: {first_track.get('audio_codec', 'N/A')}\n")
                    f.write(f"    Bitrate: {first_track.get('bitrate', 'N/A')}\n")
                    f.write(f"    Fréquence: {first_track.get('frequency', 'N/A')}\n")

            # ... (END of the filled section for writing audio data)

        print(f"\nTerminé. Le fichier d'information a été créé : '{nfo_path}'")
    except IOError as e:
        print(f"Erreur lors de l'écriture du fichier '{nfo_path}': {e}")


# --- Main Execution ---

if __name__ == "__main__":
    # Get folder path from command-line argument or user input
    if len(sys.argv) > 1:
        folder_path = sys.argv[1]
    else:
        folder_path = input("Dossier ? : ").strip().replace("'", "")

    if not os.path.isdir(folder_path):
        print(f"Erreur : Le chemin '{folder_path}' n'est pas un dossier valide.")
        sys.exit(1)

    # # Step 1: Rename files
    # rename_files_with_no_extension(folder_path)

    # Step 2 : Remove duplicates
    # filenames = {}
    # for filename in sorted(glob.glob(f'{folder_path}/*/*/*.*')):
    #     basename = os.path.splitext(filename)[0]
    #     if basename in filenames:
    #         old_file = filenames.pop(basename)
    #         print(f"Removing {old_file}")
    #         os.remove(old_file)
    #     filenames[basename] = filename

    # Step 3: Generate NFO
    generate_nfo(folder_path)
